version: "3"

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: bloodalert-uptime-kuma
    volumes:
      - ./uptime-kuma-data:/app/data
    ports:
      - 4001:3001
    restart: always
    depends_on:
      - postgres

  postgres:
    container_name: bloodalert
    image: postgres:14.5-alpine
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - ./pg-db:/var/lib/postgresql/data
